RegisterServerEvent("agri:addmoney")
AddEventHandler("agri:addmoney", function(iprice)
  TriggerEvent('es:getPlayerFromId', source, function(user)
        user:addMoney(tonumber(iprice))
  end)
end)

RegisterServerEvent("agri:getCash_s")
AddEventHandler("agri:getCash_s", function()
  TriggerEvent('es:getPlayerFromId', source, function(user)
    local argent = user:getMoney()
    TriggerClientEvent("agri:f_getCash", source, argent)
  end)
end)
